### PR TITLE
NYT

### PR DESCRIPTION
**Pull request by thankgodr**
Created a clone of NYT article Page.
The project was completed without using flexbox or grid.
Stickler installed and all test was passed.
Html Validated

### CODE REVIEW

**Comment by kobiyoyo** [comment]
### Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Comment by kobiyoyo** [comment]
## Hi Team   
#### Great Job working on _Editors’ Picks_, but there is one more thing required. 

### Page structure
#### Footer
- [ ]  Your page should have this fixed footer that sticks at the bottom (check original page)



### Make changes and submit another code review request.
*Happy coding*

**Comment by pelzolga123** [comment]
## Hi Team,
## Great  work, Congratulation :+1: 
You did all changes required previously. Go ahead and merge to master
_Goodluck in your next project_ *Happy coding*

**Comment by sergiomauz** [comment]
Thank you @kobiyoyo and @pelzolga123 ....

**Pull request merged**
